-- Mystery: 60 clicks, 3 carts (~1.2% CTR)
-- book_ids: 'the-hollow-hour', 'cold-case-protocol', 'what-the-river-knows'
INSERT INTO click_events (user_id, segment, book_id, event_type, created_at) VALUES
  (gen_random_uuid()::text, 'Mystery', 'the-hollow-hour',       'click',  now() - interval '7 days' + interval '00:11:00'),
  (gen_random_uuid()::text, 'Mystery', 'cold-case-protocol',    'click',  now() - interval '7 days' + interval '00:34:00'),
  (gen_random_uuid()::text, 'Mystery', 'what-the-river-knows',  'click',  now() - interval '7 days' + interval '01:02:00'),
  (gen_random_uuid()::text, 'Mystery', 'the-hollow-hour',       'click',  now() - interval '7 days' + interval '01:45:00'),
  (gen_random_uuid()::text, 'Mystery', 'cold-case-protocol',    'click',  now() - interval '7 days' + interval '02:17:00'),
  (gen_random_uuid()::text, 'Mystery', 'what-the-river-knows',  'click',  now() - interval '7 days' + interval '03:00:00'),
  (gen_random_uuid()::text, 'Mystery', 'the-hollow-hour',       'click',  now() - interval '6 days' + interval '00:08:00'),
  (gen_random_uuid()::text, 'Mystery', 'cold-case-protocol',    'click',  now() - interval '6 days' + interval '00:52:00'),
  (gen_random_uuid()::text, 'Mystery', 'what-the-river-knows',  'click',  now() - interval '6 days' + interval '01:30:00'),
  (gen_random_uuid()::text, 'Mystery', 'the-hollow-hour',       'click',  now() - interval '6 days' + interval '02:10:00'),
  (gen_random_uuid()::text, 'Mystery', 'cold-case-protocol',    'click',  now() - interval '6 days' + interval '03:05:00'),
  (gen_random_uuid()::text, 'Mystery', 'what-the-river-knows',  'click',  now() - interval '6 days' + interval '04:00:00'),
  (gen_random_uuid()::text, 'Mystery', 'the-hollow-hour',       'click',  now() - interval '5 days' + interval '00:20:00'),
  (gen_random_uuid()::text, 'Mystery', 'cold-case-protocol',    'click',  now() - interval '5 days' + interval '01:10:00'),
  (gen_random_uuid()::text, 'Mystery', 'what-the-river-knows',  'click',  now() - interval '5 days' + interval '02:00:00'),
  (gen_random_uuid()::text, 'Mystery', 'the-hollow-hour',       'click',  now() - interval '5 days' + interval '02:55:00'),
  (gen_random_uuid()::text, 'Mystery', 'cold-case-protocol',    'click',  now() - interval '5 days' + interval '03:40:00'),
  (gen_random_uuid()::text, 'Mystery', 'what-the-river-knows',  'click',  now() - interval '5 days' + interval '04:30:00'),
  (gen_random_uuid()::text, 'Mystery', 'the-hollow-hour',       'click',  now() - interval '4 days' + interval '00:15:00'),
  (gen_random_uuid()::text, 'Mystery', 'cold-case-protocol',    'click',  now() - interval '4 days' + interval '01:05:00'),
  (gen_random_uuid()::text, 'Mystery', 'what-the-river-knows',  'click',  now() - interval '4 days' + interval '01:55:00'),
  (gen_random_uuid()::text, 'Mystery', 'the-hollow-hour',       'click',  now() - interval '4 days' + interval '02:45:00'),
  (gen_random_uuid()::text, 'Mystery', 'cold-case-protocol',    'click',  now() - interval '4 days' + interval '03:35:00'),
  (gen_random_uuid()::text, 'Mystery', 'what-the-river-knows',  'click',  now() - interval '4 days' + interval '04:25:00'),
  (gen_random_uuid()::text, 'Mystery', 'the-hollow-hour',       'click',  now() - interval '3 days' + interval '00:18:00'),
  (gen_random_uuid()::text, 'Mystery', 'cold-case-protocol',    'click',  now() - interval '3 days' + interval '01:08:00'),
  (gen_random_uuid()::text, 'Mystery', 'what-the-river-knows',  'click',  now() - interval '3 days' + interval '01:58:00'),
  (gen_random_uuid()::text, 'Mystery', 'the-hollow-hour',       'click',  now() - interval '3 days' + interval '02:48:00'),
  (gen_random_uuid()::text, 'Mystery', 'cold-case-protocol',    'click',  now() - interval '3 days' + interval '03:38:00'),
  (gen_random_uuid()::text, 'Mystery', 'what-the-river-knows',  'click',  now() - interval '3 days' + interval '04:28:00'),
  (gen_random_uuid()::text, 'Mystery', 'the-hollow-hour',       'click',  now() - interval '2 days' + interval '00:12:00'),
  (gen_random_uuid()::text, 'Mystery', 'cold-case-protocol',    'click',  now() - interval '2 days' + interval '01:02:00'),
  (gen_random_uuid()::text, 'Mystery', 'what-the-river-knows',  'click',  now() - interval '2 days' + interval '01:52:00'),
  (gen_random_uuid()::text, 'Mystery', 'the-hollow-hour',       'click',  now() - interval '2 days' + interval '02:42:00'),
  (gen_random_uuid()::text, 'Mystery', 'cold-case-protocol',    'click',  now() - interval '2 days' + interval '03:32:00'),
  (gen_random_uuid()::text, 'Mystery', 'what-the-river-knows',  'click',  now() - interval '2 days' + interval '04:22:00'),
  (gen_random_uuid()::text, 'Mystery', 'the-hollow-hour',       'click',  now() - interval '1 day'  + interval '00:09:00'),
  (gen_random_uuid()::text, 'Mystery', 'cold-case-protocol',    'click',  now() - interval '1 day'  + interval '00:59:00'),
  (gen_random_uuid()::text, 'Mystery', 'what-the-river-knows',  'click',  now() - interval '1 day'  + interval '01:49:00'),
  (gen_random_uuid()::text, 'Mystery', 'the-hollow-hour',       'click',  now() - interval '1 day'  + interval '02:39:00'),
  (gen_random_uuid()::text, 'Mystery', 'cold-case-protocol',    'click',  now() - interval '1 day'  + interval '03:29:00'),
  (gen_random_uuid()::text, 'Mystery', 'what-the-river-knows',  'click',  now() - interval '1 day'  + interval '04:19:00'),
  (gen_random_uuid()::text, 'Mystery', 'the-hollow-hour',       'click',  now() - interval '12 hours'),
  (gen_random_uuid()::text, 'Mystery', 'cold-case-protocol',    'click',  now() - interval '10 hours'),
  (gen_random_uuid()::text, 'Mystery', 'what-the-river-knows',  'click',  now() - interval '8 hours'),
  (gen_random_uuid()::text, 'Mystery', 'the-hollow-hour',       'click',  now() - interval '6 hours'),
  (gen_random_uuid()::text, 'Mystery', 'cold-case-protocol',    'click',  now() - interval '4 hours'),
  (gen_random_uuid()::text, 'Mystery', 'what-the-river-knows',  'click',  now() - interval '3 hours'),
  (gen_random_uuid()::text, 'Mystery', 'the-hollow-hour',       'click',  now() - interval '2 hours'),
  (gen_random_uuid()::text, 'Mystery', 'cold-case-protocol',    'click',  now() - interval '90 minutes'),
  (gen_random_uuid()::text, 'Mystery', 'what-the-river-knows',  'click',  now() - interval '75 minutes'),
  (gen_random_uuid()::text, 'Mystery', 'the-hollow-hour',       'click',  now() - interval '60 minutes'),
  (gen_random_uuid()::text, 'Mystery', 'cold-case-protocol',    'click',  now() - interval '45 minutes'),
  (gen_random_uuid()::text, 'Mystery', 'what-the-river-knows',  'click',  now() - interval '30 minutes'),
  (gen_random_uuid()::text, 'Mystery', 'the-hollow-hour',       'click',  now() - interval '20 minutes'),
  (gen_random_uuid()::text, 'Mystery', 'cold-case-protocol',    'click',  now() - interval '15 minutes'),
  (gen_random_uuid()::text, 'Mystery', 'what-the-river-knows',  'click',  now() - interval '10 minutes'),
  (gen_random_uuid()::text, 'Mystery', 'the-hollow-hour',       'click',  now() - interval '7 minutes'),
  (gen_random_uuid()::text, 'Mystery', 'cold-case-protocol',    'click',  now() - interval '5 minutes'),
  (gen_random_uuid()::text, 'Mystery', 'what-the-river-knows',  'click',  now() - interval '2 minutes'),
  -- Mystery carts (3 total)
  (gen_random_uuid()::text, 'Mystery', 'what-the-river-knows',  'cart',   now() - interval '5 days' + interval '02:30:00'),
  (gen_random_uuid()::text, 'Mystery', 'the-hollow-hour',       'cart',   now() - interval '2 days' + interval '01:15:00'),
  (gen_random_uuid()::text, 'Mystery', 'cold-case-protocol',    'cart',   now() - interval '1 day'  + interval '03:00:00');

-- Romance: 70 clicks, 20 carts (~4.8% CTR)
INSERT INTO click_events (user_id, segment, book_id, event_type, created_at) VALUES
  (gen_random_uuid()::text, 'Romance', 'the-love-hypothesis',   'click',  now() - interval '7 days' + interval '00:05:00'),
  (gen_random_uuid()::text, 'Romance', 'beach-read',            'click',  now() - interval '7 days' + interval '00:25:00'),
  (gen_random_uuid()::text, 'Romance', 'people-we-meet-on-vacation','click', now() - interval '7 days' + interval '00:50:00'),
  (gen_random_uuid()::text, 'Romance', 'the-love-hypothesis',   'click',  now() - interval '7 days' + interval '01:20:00'),
  (gen_random_uuid()::text, 'Romance', 'beach-read',            'click',  now() - interval '7 days' + interval '01:55:00'),
  (gen_random_uuid()::text, 'Romance', 'people-we-meet-on-vacation','click', now() - interval '7 days' + interval '02:30:00'),
  (gen_random_uuid()::text, 'Romance', 'the-love-hypothesis',   'click',  now() - interval '7 days' + interval '03:10:00'),
  (gen_random_uuid()::text, 'Romance', 'beach-read',            'click',  now() - interval '7 days' + interval '03:50:00'),
  (gen_random_uuid()::text, 'Romance', 'people-we-meet-on-vacation','click', now() - interval '7 days' + interval '04:30:00'),
  (gen_random_uuid()::text, 'Romance', 'the-love-hypothesis',   'click',  now() - interval '7 days' + interval '05:10:00'),
  (gen_random_uuid()::text, 'Romance', 'beach-read',            'click',  now() - interval '6 days' + interval '00:10:00'),
  (gen_random_uuid()::text, 'Romance', 'people-we-meet-on-vacation','click', now() - interval '6 days' + interval '00:45:00'),
  (gen_random_uuid()::text, 'Romance', 'the-love-hypothesis',   'click',  now() - interval '6 days' + interval '01:20:00'),
  (gen_random_uuid()::text, 'Romance', 'beach-read',            'click',  now() - interval '6 days' + interval '01:55:00'),
  (gen_random_uuid()::text, 'Romance', 'people-we-meet-on-vacation','click', now() - interval '6 days' + interval '02:35:00'),
  (gen_random_uuid()::text, 'Romance', 'the-love-hypothesis',   'click',  now() - interval '6 days' + interval '03:15:00'),
  (gen_random_uuid()::text, 'Romance', 'beach-read',            'click',  now() - interval '6 days' + interval '03:55:00'),
  (gen_random_uuid()::text, 'Romance', 'people-we-meet-on-vacation','click', now() - interval '6 days' + interval '04:35:00'),
  (gen_random_uuid()::text, 'Romance', 'the-love-hypothesis',   'click',  now() - interval '6 days' + interval '05:15:00'),
  (gen_random_uuid()::text, 'Romance', 'beach-read',            'click',  now() - interval '6 days' + interval '05:55:00'),
  (gen_random_uuid()::text, 'Romance', 'people-we-meet-on-vacation','click', now() - interval '5 days' + interval '00:30:00'),
  (gen_random_uuid()::text, 'Romance', 'the-love-hypothesis',   'click',  now() - interval '5 days' + interval '01:10:00'),
  (gen_random_uuid()::text, 'Romance', 'beach-read',            'click',  now() - interval '5 days' + interval '01:50:00'),
  (gen_random_uuid()::text, 'Romance', 'people-we-meet-on-vacation','click', now() - interval '5 days' + interval '02:30:00'),
  (gen_random_uuid()::text, 'Romance', 'the-love-hypothesis',   'click',  now() - interval '5 days' + interval '03:10:00'),
  (gen_random_uuid()::text, 'Romance', 'beach-read',            'click',  now() - interval '5 days' + interval '03:50:00'),
  (gen_random_uuid()::text, 'Romance', 'people-we-meet-on-vacation','click', now() - interval '5 days' + interval '04:30:00'),
  (gen_random_uuid()::text, 'Romance', 'the-love-hypothesis',   'click',  now() - interval '5 days' + interval '05:10:00'),
  (gen_random_uuid()::text, 'Romance', 'beach-read',            'click',  now() - interval '5 days' + interval '05:50:00'),
  (gen_random_uuid()::text, 'Romance', 'people-we-meet-on-vacation','click', now() - interval '5 days' + interval '06:30:00'),
  (gen_random_uuid()::text, 'Romance', 'the-love-hypothesis',   'click',  now() - interval '4 days' + interval '00:15:00'),
  (gen_random_uuid()::text, 'Romance', 'beach-read',            'click',  now() - interval '4 days' + interval '00:55:00'),
  (gen_random_uuid()::text, 'Romance', 'people-we-meet-on-vacation','click', now() - interval '4 days' + interval '01:35:00'),
  (gen_random_uuid()::text, 'Romance', 'the-love-hypothesis',   'click',  now() - interval '4 days' + interval '02:15:00'),
  (gen_random_uuid()::text, 'Romance', 'beach-read',            'click',  now() - interval '4 days' + interval '02:55:00'),
  (gen_random_uuid()::text, 'Romance', 'people-we-meet-on-vacation','click', now() - interval '4 days' + interval '03:35:00'),
  (gen_random_uuid()::text, 'Romance', 'the-love-hypothesis',   'click',  now() - interval '4 days' + interval '04:15:00'),
  (gen_random_uuid()::text, 'Romance', 'beach-read',            'click',  now() - interval '4 days' + interval '04:55:00'),
  (gen_random_uuid()::text, 'Romance', 'people-we-meet-on-vacation','click', now() - interval '4 days' + interval '05:35:00'),
  (gen_random_uuid()::text, 'Romance', 'the-love-hypothesis',   'click',  now() - interval '4 days' + interval '06:15:00'),
  (gen_random_uuid()::text, 'Romance', 'beach-read',            'click',  now() - interval '3 days' + interval '00:20:00'),
  (gen_random_uuid()::text, 'Romance', 'people-we-meet-on-vacation','click', now() - interval '3 days' + interval '01:00:00'),
  (gen_random_uuid()::text, 'Romance', 'the-love-hypothesis',   'click',  now() - interval '3 days' + interval '01:40:00'),
  (gen_random_uuid()::text, 'Romance', 'beach-read',            'click',  now() - interval '3 days' + interval '02:20:00'),
  (gen_random_uuid()::text, 'Romance', 'people-we-meet-on-vacation','click', now() - interval '3 days' + interval '03:00:00'),
  (gen_random_uuid()::text, 'Romance', 'the-love-hypothesis',   'click',  now() - interval '3 days' + interval '03:40:00'),
  (gen_random_uuid()::text, 'Romance', 'beach-read',            'click',  now() - interval '3 days' + interval '04:20:00'),
  (gen_random_uuid()::text, 'Romance', 'people-we-meet-on-vacation','click', now() - interval '3 days' + interval '05:00:00'),
  (gen_random_uuid()::text, 'Romance', 'the-love-hypothesis',   'click',  now() - interval '3 days' + interval '05:40:00'),
  (gen_random_uuid()::text, 'Romance', 'beach-read',            'click',  now() - interval '3 days' + interval '06:20:00'),
  (gen_random_uuid()::text, 'Romance', 'the-love-hypothesis',   'click',  now() - interval '2 days' + interval '00:30:00'),
  (gen_random_uuid()::text, 'Romance', 'beach-read',            'click',  now() - interval '2 days' + interval '01:10:00'),
  (gen_random_uuid()::text, 'Romance', 'people-we-meet-on-vacation','click', now() - interval '2 days' + interval '01:50:00'),
  (gen_random_uuid()::text, 'Romance', 'the-love-hypothesis',   'click',  now() - interval '2 days' + interval '02:30:00'),
  (gen_random_uuid()::text, 'Romance', 'beach-read',            'click',  now() - interval '2 days' + interval '03:10:00'),
  (gen_random_uuid()::text, 'Romance', 'people-we-meet-on-vacation','click', now() - interval '2 days' + interval '03:50:00'),
  (gen_random_uuid()::text, 'Romance', 'the-love-hypothesis',   'click',  now() - interval '1 day'  + interval '00:40:00'),
  (gen_random_uuid()::text, 'Romance', 'beach-read',            'click',  now() - interval '1 day'  + interval '01:20:00'),
  (gen_random_uuid()::text, 'Romance', 'people-we-meet-on-vacation','click', now() - interval '1 day'  + interval '02:00:00'),
  (gen_random_uuid()::text, 'Romance', 'the-love-hypothesis',   'click',  now() - interval '1 day'  + interval '02:40:00'),
  (gen_random_uuid()::text, 'Romance', 'beach-read',            'click',  now() - interval '1 day'  + interval '03:20:00'),
  (gen_random_uuid()::text, 'Romance', 'people-we-meet-on-vacation','click', now() - interval '8 hours'),
  (gen_random_uuid()::text, 'Romance', 'the-love-hypothesis',   'click',  now() - interval '5 hours'),
  (gen_random_uuid()::text, 'Romance', 'beach-read',            'click',  now() - interval '3 hours'),
  (gen_random_uuid()::text, 'Romance', 'people-we-meet-on-vacation','click', now() - interval '2 hours'),
  (gen_random_uuid()::text, 'Romance', 'the-love-hypothesis',   'click',  now() - interval '1 hour'),
  (gen_random_uuid()::text, 'Romance', 'beach-read',            'click',  now() - interval '30 minutes'),
  (gen_random_uuid()::text, 'Romance', 'people-we-meet-on-vacation','click', now() - interval '15 minutes'),
  (gen_random_uuid()::text, 'Romance', 'the-love-hypothesis',   'click',  now() - interval '5 minutes'),
  -- Romance carts (20 total)
  (gen_random_uuid()::text, 'Romance', 'the-love-hypothesis',   'cart',   now() - interval '7 days' + interval '02:00:00'),
  (gen_random_uuid()::text, 'Romance', 'beach-read',            'cart',   now() - interval '7 days' + interval '04:00:00'),
  (gen_random_uuid()::text, 'Romance', 'people-we-meet-on-vacation','cart', now() - interval '6 days' + interval '01:00:00'),
  (gen_random_uuid()::text, 'Romance', 'the-love-hypothesis',   'cart',   now() - interval '6 days' + interval '03:00:00'),
  (gen_random_uuid()::text, 'Romance', 'beach-read',            'cart',   now() - interval '6 days' + interval '05:00:00'),
  (gen_random_uuid()::text, 'Romance', 'people-we-meet-on-vacation','cart', now() - interval '5 days' + interval '01:30:00'),
  (gen_random_uuid()::text, 'Romance', 'the-love-hypothesis',   'cart',   now() - interval '5 days' + interval '03:30:00'),
  (gen_random_uuid()::text, 'Romance', 'beach-read',            'cart',   now() - interval '5 days' + interval '05:30:00'),
  (gen_random_uuid()::text, 'Romance', 'people-we-meet-on-vacation','cart', now() - interval '4 days' + interval '01:00:00'),
  (gen_random_uuid()::text, 'Romance', 'the-love-hypothesis',   'cart',   now() - interval '4 days' + interval '03:00:00'),
  (gen_random_uuid()::text, 'Romance', 'beach-read',            'cart',   now() - interval '4 days' + interval '05:00:00'),
  (gen_random_uuid()::text, 'Romance', 'people-we-meet-on-vacation','cart', now() - interval '3 days' + interval '02:00:00'),
  (gen_random_uuid()::text, 'Romance', 'the-love-hypothesis',   'cart',   now() - interval '3 days' + interval '04:00:00'),
  (gen_random_uuid()::text, 'Romance', 'beach-read',            'cart',   now() - interval '3 days' + interval '06:00:00'),
  (gen_random_uuid()::text, 'Romance', 'people-we-meet-on-vacation','cart', now() - interval '2 days' + interval '01:00:00'),
  (gen_random_uuid()::text, 'Romance', 'the-love-hypothesis',   'cart',   now() - interval '2 days' + interval '03:00:00'),
  (gen_random_uuid()::text, 'Romance', 'beach-read',            'cart',   now() - interval '2 days' + interval '05:00:00'),
  (gen_random_uuid()::text, 'Romance', 'people-we-meet-on-vacation','cart', now() - interval '1 day'  + interval '02:00:00'),
  (gen_random_uuid()::text, 'Romance', 'the-love-hypothesis',   'cart',   now() - interval '1 day'  + interval '04:00:00'),
  (gen_random_uuid()::text, 'Romance', 'beach-read',            'cart',   now() - interval '4 hours');

-- Sci-Fi: 60 clicks, 18 carts (~4.2% CTR)
INSERT INTO click_events (user_id, segment, book_id, event_type, created_at) VALUES
  (gen_random_uuid()::text, 'Sci-Fi', 'project-hail-mary',     'click',  now() - interval '7 days' + interval '00:07:00'),
  (gen_random_uuid()::text, 'Sci-Fi', 'the-martian',           'click',  now() - interval '7 days' + interval '00:40:00'),
  (gen_random_uuid()::text, 'Sci-Fi', 'dune',                  'click',  now() - interval '7 days' + interval '01:15:00'),
  (gen_random_uuid()::text, 'Sci-Fi', 'project-hail-mary',     'click',  now() - interval '7 days' + interval '01:55:00'),
  (gen_random_uuid()::text, 'Sci-Fi', 'the-martian',           'click',  now() - interval '7 days' + interval '02:40:00'),
  (gen_random_uuid()::text, 'Sci-Fi', 'dune',                  'click',  now() - interval '7 days' + interval '03:25:00'),
  (gen_random_uuid()::text, 'Sci-Fi', 'project-hail-mary',     'click',  now() - interval '7 days' + interval '04:10:00'),
  (gen_random_uuid()::text, 'Sci-Fi', 'the-martian',           'click',  now() - interval '7 days' + interval '04:55:00'),
  (gen_random_uuid()::text, 'Sci-Fi', 'dune',                  'click',  now() - interval '6 days' + interval '00:10:00'),
  (gen_random_uuid()::text, 'Sci-Fi', 'project-hail-mary',     'click',  now() - interval '6 days' + interval '00:55:00'),
  (gen_random_uuid()::text, 'Sci-Fi', 'the-martian',           'click',  now() - interval '6 days' + interval '01:45:00'),
  (gen_random_uuid()::text, 'Sci-Fi', 'dune',                  'click',  now() - interval '6 days' + interval '02:35:00'),
  (gen_random_uuid()::text, 'Sci-Fi', 'project-hail-mary',     'click',  now() - interval '6 days' + interval '03:25:00'),
  (gen_random_uuid()::text, 'Sci-Fi', 'the-martian',           'click',  now() - interval '6 days' + interval '04:15:00'),
  (gen_random_uuid()::text, 'Sci-Fi', 'dune',                  'click',  now() - interval '5 days' + interval '00:15:00'),
  (gen_random_uuid()::text, 'Sci-Fi', 'project-hail-mary',     'click',  now() - interval '5 days' + interval '01:05:00'),
  (gen_random_uuid()::text, 'Sci-Fi', 'the-martian',           'click',  now() - interval '5 days' + interval '01:55:00'),
  (gen_random_uuid()::text, 'Sci-Fi', 'dune',                  'click',  now() - interval '5 days' + interval '02:45:00'),
  (gen_random_uuid()::text, 'Sci-Fi', 'project-hail-mary',     'click',  now() - interval '5 days' + interval '03:35:00'),
  (gen_random_uuid()::text, 'Sci-Fi', 'the-martian',           'click',  now() - interval '5 days' + interval '04:25:00'),
  (gen_random_uuid()::text, 'Sci-Fi', 'dune',                  'click',  now() - interval '4 days' + interval '00:20:00'),
  (gen_random_uuid()::text, 'Sci-Fi', 'project-hail-mary',     'click',  now() - interval '4 days' + interval '01:10:00'),
  (gen_random_uuid()::text, 'Sci-Fi', 'the-martian',           'click',  now() - interval '4 days' + interval '02:00:00'),
  (gen_random_uuid()::text, 'Sci-Fi', 'dune',                  'click',  now() - interval '4 days' + interval '02:50:00'),
  (gen_random_uuid()::text, 'Sci-Fi', 'project-hail-mary',     'click',  now() - interval '4 days' + interval '03:40:00'),
  (gen_random_uuid()::text, 'Sci-Fi', 'the-martian',           'click',  now() - interval '4 days' + interval '04:30:00'),
  (gen_random_uuid()::text, 'Sci-Fi', 'dune',                  'click',  now() - interval '3 days' + interval '00:25:00'),
  (gen_random_uuid()::text, 'Sci-Fi', 'project-hail-mary',     'click',  now() - interval '3 days' + interval '01:15:00'),
  (gen_random_uuid()::text, 'Sci-Fi', 'the-martian',           'click',  now() - interval '3 days' + interval '02:05:00'),
  (gen_random_uuid()::text, 'Sci-Fi', 'dune',                  'click',  now() - interval '3 days' + interval '02:55:00'),
  (gen_random_uuid()::text, 'Sci-Fi', 'project-hail-mary',     'click',  now() - interval '3 days' + interval '03:45:00'),
  (gen_random_uuid()::text, 'Sci-Fi', 'the-martian',           'click',  now() - interval '3 days' + interval '04:35:00'),
  (gen_random_uuid()::text, 'Sci-Fi', 'dune',                  'click',  now() - interval '2 days' + interval '00:30:00'),
  (gen_random_uuid()::text, 'Sci-Fi', 'project-hail-mary',     'click',  now() - interval '2 days' + interval '01:20:00'),
  (gen_random_uuid()::text, 'Sci-Fi', 'the-martian',           'click',  now() - interval '2 days' + interval '02:10:00'),
  (gen_random_uuid()::text, 'Sci-Fi', 'dune',                  'click',  now() - interval '2 days' + interval '03:00:00'),
  (gen_random_uuid()::text, 'Sci-Fi', 'project-hail-mary',     'click',  now() - interval '2 days' + interval '03:50:00'),
  (gen_random_uuid()::text, 'Sci-Fi', 'the-martian',           'click',  now() - interval '2 days' + interval '04:40:00'),
  (gen_random_uuid()::text, 'Sci-Fi', 'dune',                  'click',  now() - interval '1 day'  + interval '00:35:00'),
  (gen_random_uuid()::text, 'Sci-Fi', 'project-hail-mary',     'click',  now() - interval '1 day'  + interval '01:25:00'),
  (gen_random_uuid()::text, 'Sci-Fi', 'the-martian',           'click',  now() - interval '1 day'  + interval '02:15:00'),
  (gen_random_uuid()::text, 'Sci-Fi', 'dune',                  'click',  now() - interval '1 day'  + interval '03:05:00'),
  (gen_random_uuid()::text, 'Sci-Fi', 'project-hail-mary',     'click',  now() - interval '1 day'  + interval '03:55:00'),
  (gen_random_uuid()::text, 'Sci-Fi', 'the-martian',           'click',  now() - interval '1 day'  + interval '04:45:00'),
  (gen_random_uuid()::text, 'Sci-Fi', 'dune',                  'click',  now() - interval '11 hours'),
  (gen_random_uuid()::text, 'Sci-Fi', 'project-hail-mary',     'click',  now() - interval '9 hours'),
  (gen_random_uuid()::text, 'Sci-Fi', 'the-martian',           'click',  now() - interval '7 hours'),
  (gen_random_uuid()::text, 'Sci-Fi', 'dune',                  'click',  now() - interval '5 hours'),
  (gen_random_uuid()::text, 'Sci-Fi', 'project-hail-mary',     'click',  now() - interval '3 hours'),
  (gen_random_uuid()::text, 'Sci-Fi', 'the-martian',           'click',  now() - interval '2 hours'),
  (gen_random_uuid()::text, 'Sci-Fi', 'dune',                  'click',  now() - interval '90 minutes'),
  (gen_random_uuid()::text, 'Sci-Fi', 'project-hail-mary',     'click',  now() - interval '70 minutes'),
  (gen_random_uuid()::text, 'Sci-Fi', 'the-martian',           'click',  now() - interval '50 minutes'),
  (gen_random_uuid()::text, 'Sci-Fi', 'dune',                  'click',  now() - interval '35 minutes'),
  (gen_random_uuid()::text, 'Sci-Fi', 'project-hail-mary',     'click',  now() - interval '25 minutes'),
  (gen_random_uuid()::text, 'Sci-Fi', 'the-martian',           'click',  now() - interval '18 minutes'),
  (gen_random_uuid()::text, 'Sci-Fi', 'dune',                  'click',  now() - interval '12 minutes'),
  (gen_random_uuid()::text, 'Sci-Fi', 'project-hail-mary',     'click',  now() - interval '8 minutes'),
  (gen_random_uuid()::text, 'Sci-Fi', 'the-martian',           'click',  now() - interval '4 minutes'),
  (gen_random_uuid()::text, 'Sci-Fi', 'dune',                  'click',  now() - interval '1 minute'),
  -- Sci-Fi carts (18 total)
  (gen_random_uuid()::text, 'Sci-Fi', 'project-hail-mary',     'cart',   now() - interval '7 days' + interval '02:00:00'),
  (gen_random_uuid()::text, 'Sci-Fi', 'the-martian',           'cart',   now() - interval '7 days' + interval '04:00:00'),
  (gen_random_uuid()::text, 'Sci-Fi', 'dune',                  'cart',   now() - interval '6 days' + interval '01:30:00'),
  (gen_random_uuid()::text, 'Sci-Fi', 'project-hail-mary',     'cart',   now() - interval '6 days' + interval '03:30:00'),
  (gen_random_uuid()::text, 'Sci-Fi', 'the-martian',           'cart',   now() - interval '5 days' + interval '01:00:00'),
  (gen_random_uuid()::text, 'Sci-Fi', 'dune',                  'cart',   now() - interval '5 days' + interval '03:00:00'),
  (gen_random_uuid()::text, 'Sci-Fi', 'project-hail-mary',     'cart',   now() - interval '4 days' + interval '01:30:00'),
  (gen_random_uuid()::text, 'Sci-Fi', 'the-martian',           'cart',   now() - interval '4 days' + interval '03:30:00'),
  (gen_random_uuid()::text, 'Sci-Fi', 'dune',                  'cart',   now() - interval '4 days' + interval '05:30:00'),
  (gen_random_uuid()::text, 'Sci-Fi', 'project-hail-mary',     'cart',   now() - interval '3 days' + interval '02:00:00'),
  (gen_random_uuid()::text, 'Sci-Fi', 'the-martian',           'cart',   now() - interval '3 days' + interval '04:00:00'),
  (gen_random_uuid()::text, 'Sci-Fi', 'dune',                  'cart',   now() - interval '2 days' + interval '01:00:00'),
  (gen_random_uuid()::text, 'Sci-Fi', 'project-hail-mary',     'cart',   now() - interval '2 days' + interval '03:00:00'),
  (gen_random_uuid()::text, 'Sci-Fi', 'the-martian',           'cart',   now() - interval '2 days' + interval '05:00:00'),
  (gen_random_uuid()::text, 'Sci-Fi', 'dune',                  'cart',   now() - interval '1 day'  + interval '01:00:00'),
  (gen_random_uuid()::text, 'Sci-Fi', 'project-hail-mary',     'cart',   now() - interval '1 day'  + interval '03:00:00'),
  (gen_random_uuid()::text, 'Sci-Fi', 'the-martian',           'cart',   now() - interval '1 day'  + interval '05:00:00'),
  (gen_random_uuid()::text, 'Sci-Fi', 'dune',                  'cart',   now() - interval '6 hours');
