import type { RunEvent, DemoSite } from "./types";

type ScriptEvent = RunEvent;

// ── PageTurn scripts ──────────────────────────────────────────────────────────

const PAGETURN_ALL: ScriptEvent[] = [
  { t: 0,     type: "run.start",      goal: "__GOAL__" },
  { t: 100,   type: "node.active",    node: "fetch" },
  { t: 250,   type: "thought",        agent: "analyst",   text: "Connecting to Supabase…" },
  { t: 600,   type: "thought",        agent: "analyst",   text: "Pulling 1,247 click events from last 24h" },
  { t: 1100,  type: "thought",        agent: "analyst",   text: "Mystery: 1.2% CTR · Romance: 3.4% · Sci-Fi: 4.1%" },
  { t: 1400,  type: "node.complete",  node: "fetch" },
  { t: 1500,  type: "node.active",    node: "diagnose" },
  { t: 1800,  type: "thought",        agent: "analyst",   text: "Mystery underperforming by 67% vs Romance baseline" },
  { t: 2500,  type: "thought",        agent: "analyst",   text: "Hypothesis: tag language too literary, lacks emotional hook" },
  { t: 3000,  type: "thought",        agent: "analyst",   text: "Root cause: 'Detective Fiction' tag tests 41% lower than 'Edge-of-your-seat'" },
  { t: 3200,  type: "segment.update", segment: "Mystery", ctr: 0.012 },
  { t: 3400,  type: "node.complete",  node: "diagnose" },
  { t: 3500,  type: "node.active",    node: "generate" },
  { t: 3800,  type: "thought",        agent: "optimizer", text: "Generating new config: emotional tag set + reorder by recency" },
  { t: 5000,  type: "thought",        agent: "optimizer", text: "Config drafted: 3 tags, 3 reorder positions, layout=emotional" },
  { t: 5400,  type: "node.complete",  node: "generate" },
  { t: 5500,  type: "node.active",    node: "ab" },
  { t: 5800,  type: "thought",        agent: "optimizer", text: "Splitting Mystery traffic 50/50: control vs test" },
  { t: 6500,  type: "thought",        agent: "optimizer", text: "A/B running · 247 sessions/min sample rate" },
  { t: 7000,  type: "node.complete",  node: "ab" },
  { t: 7100,  type: "node.active",    node: "measure" },
  { t: 7400,  type: "thought",        agent: "optimizer", text: "Sample 100 · p-value drifting toward significance" },
  { t: 9000,  type: "thought",        agent: "optimizer", text: "Sample 500 · test variant +28% lift · p<0.05" },
  { t: 10200, type: "thought",        agent: "optimizer", text: "Sample 1,000 · +34.2% lift confirmed" },
  { t: 10800, type: "segment.update", segment: "Mystery", ctr: 0.0161 },
  { t: 11000, type: "ab.result",      segment: "Mystery", ctrBefore: 0.012, ctrAfter: 0.0161, winner: "test",
    rootCause: "'Detective Fiction' tag tested 41% lower than emotional alternatives. Replaced with 'Suspenseful', 'Gripping', 'Edge-of-your-seat'.",
    configJson: { tags: ["Suspenseful", "Gripping", "Edge-of-your-seat"], sort_order: ["what-the-river-knows", "the-hollow-hour", "cold-case-protocol"], layout: "emotional" },
  },
  { t: 11400, type: "thought",        agent: "optimizer", text: "Scaling test variant to 100% of Mystery traffic" },
  { t: 11800, type: "thought",        agent: "optimizer", text: "✓ Applied. Optimization complete." },
  { t: 12000, type: "node.complete",  node: "measure" },
  { t: 12200, type: "run.complete" },
];

const PAGETURN_MYSTERY: ScriptEvent[] = [
  { t: 0,     type: "run.start",      goal: "__GOAL__" },
  { t: 100,   type: "node.active",    node: "fetch" },
  { t: 250,   type: "thought",        agent: "analyst",   text: "Fetching Mystery segment data — last 7 days" },
  { t: 700,   type: "thought",        agent: "analyst",   text: "Mystery: 1,412 clicks · 3,891 impressions · 1.2% CTR" },
  { t: 1200,  type: "thought",        agent: "analyst",   text: "Top 3 titles account for 78% of impressions" },
  { t: 1500,  type: "node.complete",  node: "fetch" },
  { t: 1600,  type: "node.active",    node: "diagnose" },
  { t: 1900,  type: "thought",        agent: "analyst",   text: "Bestseller 'What the River Knows' buried at position 7" },
  { t: 2600,  type: "thought",        agent: "analyst",   text: "Cover art for top 3 titles scored low in visual engagement" },
  { t: 3100,  type: "thought",        agent: "analyst",   text: "Root cause: sort order by publish date, not popularity" },
  { t: 3300,  type: "segment.update", segment: "Mystery", ctr: 0.012 },
  { t: 3500,  type: "node.complete",  node: "diagnose" },
  { t: 3600,  type: "node.active",    node: "generate" },
  { t: 3900,  type: "thought",        agent: "optimizer", text: "Config: pin bestseller to position 1, sort rest by rating" },
  { t: 5100,  type: "thought",        agent: "optimizer", text: "Adding 'Featured' badge — drives +14% avg CTR" },
  { t: 5500,  type: "node.complete",  node: "generate" },
  { t: 5600,  type: "node.active",    node: "ab" },
  { t: 5900,  type: "thought",        agent: "optimizer", text: "50/50 split · control vs bestseller-first" },
  { t: 6600,  type: "thought",        agent: "optimizer", text: "1,100 sessions · test variant pulling ahead" },
  { t: 7100,  type: "node.complete",  node: "ab" },
  { t: 7200,  type: "node.active",    node: "measure" },
  { t: 7500,  type: "thought",        agent: "optimizer", text: "CTR test: 1.9% vs control 1.2% · +58% lift at n=400" },
  { t: 9000,  type: "thought",        agent: "optimizer", text: "Confidence 97.3% · exceeds 95% threshold" },
  { t: 10300, type: "thought",        agent: "optimizer", text: "Final lift: +45.0% · rolling out to 100%" },
  { t: 10800, type: "segment.update", segment: "Mystery", ctr: 0.0174 },
  { t: 11000, type: "ab.result",      segment: "Mystery", ctrBefore: 0.012, ctrAfter: 0.0174, winner: "test",
    rootCause: "Chronological sort buried bestseller at position 7. Pinning with Featured badge delivered +45% CTR lift.",
    configJson: { sort_by: "bestseller_first", featured_id: "what-the-river-knows", badge: "Featured", layout: "featured" },
  },
  { t: 11400, type: "thought",        agent: "optimizer", text: "Writing bestseller-first config to ui_config" },
  { t: 11800, type: "thought",        agent: "optimizer", text: "✓ Mystery shelf now leads with top performers." },
  { t: 12000, type: "node.complete",  node: "measure" },
  { t: 12200, type: "run.complete" },
];

const PAGETURN_SCIFI: ScriptEvent[] = [
  { t: 0,     type: "run.start",      goal: "__GOAL__" },
  { t: 100,   type: "node.active",    node: "fetch" },
  { t: 250,   type: "thought",        agent: "analyst",   text: "Loading Sci-Fi funnel — clicks, impressions, dwell time" },
  { t: 700,   type: "thought",        agent: "analyst",   text: "Sci-Fi: 4.1% CTR but 72% bounce · users click, then leave" },
  { t: 1200,  type: "thought",        agent: "analyst",   text: "Dwell time: 8s avg · suggests mismatch on landing" },
  { t: 1500,  type: "node.complete",  node: "fetch" },
  { t: 1600,  type: "node.active",    node: "diagnose" },
  { t: 1900,  type: "thought",        agent: "analyst",   text: "Generic imagery — misses hard sci-fi audience" },
  { t: 2600,  type: "thought",        agent: "analyst",   text: "Descriptions lead with word count, not premise" },
  { t: 3100,  type: "thought",        agent: "analyst",   text: "Root cause: page doesn't match world-building reader intent" },
  { t: 3300,  type: "segment.update", segment: "Sci-Fi",  ctr: 0.041 },
  { t: 3500,  type: "node.complete",  node: "diagnose" },
  { t: 3600,  type: "node.active",    node: "generate" },
  { t: 3900,  type: "thought",        agent: "optimizer", text: "Layout: 'immersive' mode with expanded premise descriptions" },
  { t: 5100,  type: "thought",        agent: "optimizer", text: "Hero book: top engagement in A/B history for this segment" },
  { t: 5500,  type: "node.complete",  node: "generate" },
  { t: 5600,  type: "node.active",    node: "ab" },
  { t: 5900,  type: "thought",        agent: "optimizer", text: "Splitting Sci-Fi traffic · current vs immersive layout" },
  { t: 6600,  type: "thought",        agent: "optimizer", text: "Bounce dropping in test bucket — 68% → 52% at n=200" },
  { t: 7100,  type: "node.complete",  node: "ab" },
  { t: 7200,  type: "node.active",    node: "measure" },
  { t: 7500,  type: "thought",        agent: "optimizer", text: "CTR: test 5.3% vs control 4.1% · p=0.031 at n=600" },
  { t: 9000,  type: "thought",        agent: "optimizer", text: "Confidence 96.9% · bounce rate down 24 pts" },
  { t: 10300, type: "thought",        agent: "optimizer", text: "CTR +29.3% · bounce -24pts · scaling to 100%" },
  { t: 10800, type: "segment.update", segment: "Sci-Fi",  ctr: 0.053 },
  { t: 11000, type: "ab.result",      segment: "Sci-Fi",  ctrBefore: 0.041, ctrAfter: 0.053, winner: "test",
    rootCause: "Generic imagery and word-count-first descriptions miss world-building intent. Immersive layout reduced bounce 24pts and lifted CTR 29%.",
    configJson: { layout: "immersive", hero_genre: "sci-fi", description_style: "world-building", hero_book: "sci-fi-01" },
  },
  { t: 11400, type: "thought",        agent: "optimizer", text: "Applying immersive layout to Sci-Fi shelf" },
  { t: 11800, type: "thought",        agent: "optimizer", text: "✓ Sci-Fi optimised for world-building audience." },
  { t: 12000, type: "node.complete",  node: "measure" },
  { t: 12200, type: "run.complete" },
];

const PAGETURN_ROMANCE: ScriptEvent[] = [
  { t: 0,     type: "run.start",      goal: "__GOAL__" },
  { t: 100,   type: "node.active",    node: "fetch" },
  { t: 250,   type: "thought",        agent: "analyst",   text: "Pulling Romance cart event data — last 48 hours" },
  { t: 700,   type: "thought",        agent: "analyst",   text: "Romance: 3.4% CTR (healthy) · cart-add rate 0.6% (low)" },
  { t: 1200,  type: "thought",        agent: "analyst",   text: "Scroll depth 78% — readers browse but don't convert" },
  { t: 1500,  type: "node.complete",  node: "fetch" },
  { t: 1600,  type: "node.active",    node: "diagnose" },
  { t: 1900,  type: "thought",        agent: "analyst",   text: "Add-to-cart button below the fold on 60% of devices" },
  { t: 2600,  type: "thought",        agent: "analyst",   text: "Price shown only on hover — friction before intent" },
  { t: 3100,  type: "thought",        agent: "analyst",   text: "Root cause: CTA placement and price visibility drop-off" },
  { t: 3300,  type: "segment.update", segment: "Romance", ctr: 0.034 },
  { t: 3500,  type: "node.complete",  node: "diagnose" },
  { t: 3600,  type: "node.active",    node: "generate" },
  { t: 3900,  type: "thought",        agent: "optimizer", text: "Config: inline CTA + persistent price + bundle prompt" },
  { t: 5100,  type: "thought",        agent: "optimizer", text: "Bundle: 'Add 2 more Romance, save 15%' — +22% cart in Fantasy" },
  { t: 5500,  type: "node.complete",  node: "generate" },
  { t: 5600,  type: "node.active",    node: "ab" },
  { t: 5900,  type: "thought",        agent: "optimizer", text: "A/B: hover price vs inline CTA + bundle offer" },
  { t: 6600,  type: "thought",        agent: "optimizer", text: "Cart rate: test 1.1% vs control 0.6% at n=300" },
  { t: 7100,  type: "node.complete",  node: "ab" },
  { t: 7200,  type: "node.active",    node: "measure" },
  { t: 7500,  type: "thought",        agent: "optimizer", text: "p=0.024 · cart lift consistent across devices" },
  { t: 9000,  type: "thought",        agent: "optimizer", text: "Mobile especially strong: +67% on small screens" },
  { t: 10300, type: "thought",        agent: "optimizer", text: "Final: +41.2% cart adds · rolling out to 100%" },
  { t: 10800, type: "segment.update", segment: "Romance", ctr: 0.048 },
  { t: 11000, type: "ab.result",      segment: "Romance", ctrBefore: 0.034, ctrAfter: 0.048, winner: "test",
    rootCause: "CTA below the fold and hidden price created drop-off. Inline CTA with persistent price and bundle prompt lifted cart adds 41%.",
    configJson: { cta_position: "inline", price_display: "prominent", bundle_offer: true, bundle_copy: "Add 2 more Romance, save 15%" },
  },
  { t: 11400, type: "thought",        agent: "optimizer", text: "Pushing inline CTA config to all Romance cards" },
  { t: 11800, type: "thought",        agent: "optimizer", text: "✓ Romance shelf now converts readers into buyers." },
  { t: 12000, type: "node.complete",  node: "measure" },
  { t: 12200, type: "run.complete" },
];

// ── NovaWear scripts ──────────────────────────────────────────────────────────

const NOVAWEAR_WOMENS: ScriptEvent[] = [
  { t: 0,     type: "run.start",      goal: "__GOAL__" },
  { t: 100,   type: "node.active",    node: "fetch" },
  { t: 250,   type: "thought",        agent: "analyst",   text: "Fetching session data — Women's, Men's, Sale segments" },
  { t: 700,   type: "thought",        agent: "analyst",   text: "Womens: 1.4% CTR · Mens: 3.2% · Sale: 4.8%" },
  { t: 1200,  type: "thought",        agent: "analyst",   text: "Women's = 58% of sessions, only 28% of revenue" },
  { t: 1500,  type: "node.complete",  node: "fetch" },
  { t: 1600,  type: "node.active",    node: "diagnose" },
  { t: 1900,  type: "thought",        agent: "analyst",   text: "Merino Wrap Coat not in top 3 viewed — sitting at position 5" },
  { t: 2600,  type: "thought",        agent: "analyst",   text: "New arrivals tab default — doesn't surface bestsellers" },
  { t: 3100,  type: "thought",        agent: "analyst",   text: "Root cause: Oversized Blazer (nw-03) top performer, buried at pos 4" },
  { t: 3300,  type: "segment.update", segment: "Womens",  ctr: 0.014 },
  { t: 3500,  type: "node.complete",  node: "diagnose" },
  { t: 3600,  type: "node.active",    node: "generate" },
  { t: 3900,  type: "thought",        agent: "optimizer", text: "Config: pin nw-03 to position 1 with 'New' badge" },
  { t: 5100,  type: "thought",        agent: "optimizer", text: "Default tab: Women's · editorial hero headline" },
  { t: 5500,  type: "node.complete",  node: "generate" },
  { t: 5600,  type: "node.active",    node: "ab" },
  { t: 5900,  type: "thought",        agent: "optimizer", text: "50/50 split · editorial layout vs current" },
  { t: 6600,  type: "thought",        agent: "optimizer", text: "Pinned CTR: 4.1% vs control 1.4% — strong early signal" },
  { t: 7100,  type: "node.complete",  node: "ab" },
  { t: 7200,  type: "node.active",    node: "measure" },
  { t: 7500,  type: "thought",        agent: "optimizer", text: "n=420 · p=0.017 · test leading consistently" },
  { t: 9000,  type: "thought",        agent: "optimizer", text: "Segment CTR up to 2.1% · +50% lift · confidence 98.1%" },
  { t: 10300, type: "thought",        agent: "optimizer", text: "Final: 1.4% → 2.1% · scaling to 100%" },
  { t: 10800, type: "segment.update", segment: "Womens",  ctr: 0.021 },
  { t: 11000, type: "ab.result",      segment: "Womens",  ctrBefore: 0.014, ctrAfter: 0.021, winner: "test",
    rootCause: "Oversized Blazer (nw-03) buried at position 4. Pinning with 'New' badge and setting Women's default tab lifted CTR 50%.",
    configJson: { pinned: ["nw-03"], badge: "New", active_tab: "womens", hero_variant: "editorial" },
  },
  { t: 11400, type: "thought",        agent: "optimizer", text: "Applying editorial layout to Women's collection" },
  { t: 11800, type: "thought",        agent: "optimizer", text: "✓ Women's now leads with its top performer." },
  { t: 12000, type: "node.complete",  node: "measure" },
  { t: 12200, type: "run.complete" },
];

const NOVAWEAR_SALE: ScriptEvent[] = [
  { t: 0,     type: "run.start",      goal: "__GOAL__" },
  { t: 100,   type: "node.active",    node: "fetch" },
  { t: 250,   type: "thought",        agent: "analyst",   text: "Fetching Sale funnel data — last 72 hours" },
  { t: 700,   type: "thought",        agent: "analyst",   text: "Sale: 4.8% CTR · 1.8% conversion · high intent, weak purchase" },
  { t: 1200,  type: "thought",        agent: "analyst",   text: "Avg session time 42s — intent present but not converting" },
  { t: 1500,  type: "node.complete",  node: "fetch" },
  { t: 1600,  type: "node.active",    node: "diagnose" },
  { t: 1900,  type: "thought",        agent: "analyst",   text: "No urgency signals — no end date, no stock indicators" },
  { t: 2600,  type: "thought",        agent: "analyst",   text: "CTA copy: 'View Sale' — weak language for discount shoppers" },
  { t: 3100,  type: "thought",        agent: "analyst",   text: "Root cause: no urgency, generic CTA, sale items below fold" },
  { t: 3300,  type: "segment.update", segment: "Sale",    ctr: 0.021 },
  { t: 3500,  type: "node.complete",  node: "diagnose" },
  { t: 3600,  type: "node.active",    node: "generate" },
  { t: 3900,  type: "thought",        agent: "optimizer", text: "Config: urgency banner + strong CTA + Sale tab as default" },
  { t: 5100,  type: "thought",        agent: "optimizer", text: "CTA override: 'Shop now — ends tonight' · urgency layout" },
  { t: 5500,  type: "node.complete",  node: "generate" },
  { t: 5600,  type: "node.active",    node: "ab" },
  { t: 5900,  type: "thought",        agent: "optimizer", text: "A/B: standard layout vs urgency layout on Sale segment" },
  { t: 6600,  type: "thought",        agent: "optimizer", text: "Conversion: 3.1% test vs 1.8% control at n=180 — strong signal" },
  { t: 7100,  type: "node.complete",  node: "ab" },
  { t: 7200,  type: "node.active",    node: "measure" },
  { t: 7500,  type: "thought",        agent: "optimizer", text: "p=0.009 · n=520 · test dominant across all devices" },
  { t: 9000,  type: "thought",        agent: "optimizer", text: "Conversion: 1.8% → 3.4% · CTR up to 2.9%" },
  { t: 10300, type: "thought",        agent: "optimizer", text: "Final: +61.9% lift · scaling to 100% of Sale traffic" },
  { t: 10800, type: "segment.update", segment: "Sale",    ctr: 0.034 },
  { t: 11000, type: "ab.result",      segment: "Sale",    ctrBefore: 0.021, ctrAfter: 0.034, winner: "test",
    rootCause: "No urgency and weak CTA let high-intent shoppers bounce. Urgency banner + countdown + Sale-first layout lifted conversions 62%.",
    configJson: { layout: "urgency", hero_variant: "sale", cta: "Shop now — ends tonight", active_tab: "sale" },
  },
  { t: 11400, type: "thought",        agent: "optimizer", text: "Pushing urgency layout to Sale segment" },
  { t: 11800, type: "thought",        agent: "optimizer", text: "✓ Sale page now converts with urgency-driven layout." },
  { t: 12000, type: "node.complete",  node: "measure" },
  { t: 12200, type: "run.complete" },
];

const NOVAWEAR_ACCESSORIES: ScriptEvent[] = [
  { t: 0,     type: "run.start",      goal: "__GOAL__" },
  { t: 100,   type: "node.active",    node: "fetch" },
  { t: 250,   type: "thought",        agent: "analyst",   text: "Pulling accessories funnel — cart events and scroll depth" },
  { t: 700,   type: "thought",        agent: "analyst",   text: "Accessories: 0.8% cart rate · scroll depth 34% on product cards" },
  { t: 1200,  type: "thought",        agent: "analyst",   text: "Only 3% of Men's sessions visit accessories section" },
  { t: 1500,  type: "node.complete",  node: "fetch" },
  { t: 1600,  type: "node.active",    node: "diagnose" },
  { t: 1900,  type: "thought",        agent: "analyst",   text: "Accessories below fold — users don't reach it organically" },
  { t: 2600,  type: "thought",        agent: "analyst",   text: "Leather Belt (nw-09) highest-margin · gets 0.4% of product views" },
  { t: 3100,  type: "thought",        agent: "analyst",   text: "Root cause: no cross-sell, no tab prominence, buried section" },
  { t: 3300,  type: "segment.update", segment: "Accessories", ctr: 0.008 },
  { t: 3500,  type: "node.complete",  node: "diagnose" },
  { t: 3600,  type: "node.active",    node: "generate" },
  { t: 3900,  type: "thought",        agent: "optimizer", text: "Config: pin nw-09, 'Limited' badge, cross-sell on Men's + Women's" },
  { t: 5100,  type: "thought",        agent: "optimizer", text: "Cross-sell at scroll 60% — proven optimal in prior tests" },
  { t: 5500,  type: "node.complete",  node: "generate" },
  { t: 5600,  type: "node.active",    node: "ab" },
  { t: 5900,  type: "thought",        agent: "optimizer", text: "50/50 split · current vs cross-sell layout" },
  { t: 6600,  type: "thought",        agent: "optimizer", text: "Belt views up 8× in test · 'Limited' badge driving urgency" },
  { t: 7100,  type: "node.complete",  node: "ab" },
  { t: 7200,  type: "node.active",    node: "measure" },
  { t: 7500,  type: "thought",        agent: "optimizer", text: "Cart rate: 1.4% test vs 0.8% control · p=0.028 at n=350" },
  { t: 9000,  type: "thought",        agent: "optimizer", text: "12% of Men's sessions now clicking into accessories" },
  { t: 10300, type: "thought",        agent: "optimizer", text: "Final: +75% cart rate · scaling to 100%" },
  { t: 10800, type: "segment.update", segment: "Accessories", ctr: 0.014 },
  { t: 11000, type: "ab.result",      segment: "Accessories", ctrBefore: 0.008, ctrAfter: 0.014, winner: "test",
    rootCause: "Accessories lacked discoverability. Pinning Leather Belt with 'Limited' badge and cross-sell placements lifted cart rate 75%.",
    configJson: { pinned: ["nw-09"], badge: "Limited", layout: "cross-sell" },
  },
  { t: 11400, type: "thought",        agent: "optimizer", text: "Applying cross-sell layout across all categories" },
  { t: 11800, type: "thought",        agent: "optimizer", text: "✓ Accessories now discoverable at peak intent moments." },
  { t: 12000, type: "node.complete",  node: "measure" },
  { t: 12200, type: "run.complete" },
];

const NOVAWEAR_MENS: ScriptEvent[] = [
  { t: 0,     type: "run.start",      goal: "__GOAL__" },
  { t: 100,   type: "node.active",    node: "fetch" },
  { t: 250,   type: "thought",        agent: "analyst",   text: "Loading Men's — sessions, bounce, engagement heatmap" },
  { t: 700,   type: "thought",        agent: "analyst",   text: "Mens: 1.8% CTR · 64% bounce · 18s avg dwell time" },
  { t: 1200,  type: "thought",        agent: "analyst",   text: "80% of clicks land in first 3 product slots" },
  { t: 1500,  type: "node.complete",  node: "fetch" },
  { t: 1600,  type: "node.active",    node: "diagnose" },
  { t: 1900,  type: "thought",        agent: "analyst",   text: "Top slot: Straight Chinos — low visual impact, not a hero piece" },
  { t: 2600,  type: "thought",        agent: "analyst",   text: "Hero headline generic: 'Men's Collection' — no editorial voice" },
  { t: 3100,  type: "thought",        agent: "analyst",   text: "Root cause: Suit Jacket (nw-07) is the hero but sits at position 3" },
  { t: 3300,  type: "segment.update", segment: "Mens",    ctr: 0.018 },
  { t: 3500,  type: "node.complete",  node: "diagnose" },
  { t: 3600,  type: "node.active",    node: "generate" },
  { t: 3900,  type: "thought",        agent: "optimizer", text: "Config: pin nw-07 to pos 1, Men's tab default, new hero variant" },
  { t: 5100,  type: "thought",        agent: "optimizer", text: "Headline: 'Considered pieces for considered dressing'" },
  { t: 5500,  type: "node.complete",  node: "generate" },
  { t: 5600,  type: "node.active",    node: "ab" },
  { t: 5900,  type: "thought",        agent: "optimizer", text: "A/B: current layout vs editorial-first config" },
  { t: 6600,  type: "thought",        agent: "optimizer", text: "Bounce dropping: test 48% vs control 64% at n=290" },
  { t: 7100,  type: "node.complete",  node: "ab" },
  { t: 7200,  type: "node.active",    node: "measure" },
  { t: 7500,  type: "thought",        agent: "optimizer", text: "CTR: 2.6% test vs 1.8% control · p=0.031 · n=640" },
  { t: 9000,  type: "thought",        agent: "optimizer", text: "Suit Jacket getting 3.1× more views in test bucket" },
  { t: 10300, type: "thought",        agent: "optimizer", text: "Final: +44.4% CTR · bounce -16pts · scaling to 100%" },
  { t: 10800, type: "segment.update", segment: "Mens",    ctr: 0.026 },
  { t: 11000, type: "ab.result",      segment: "Mens",    ctrBefore: 0.018, ctrAfter: 0.026, winner: "test",
    rootCause: "Chinos in hero slot buried the Suit Jacket (nw-07) at position 3. Editorial hero cut bounce 16pts and lifted CTR 44%.",
    configJson: { active_tab: "mens", pinned: ["nw-07"], hero_variant: "mens" },
  },
  { t: 11400, type: "thought",        agent: "optimizer", text: "Pushing Men's editorial config — hero + tab updated" },
  { t: 11800, type: "thought",        agent: "optimizer", text: "✓ Men's now leads with its most compelling piece." },
  { t: 12000, type: "node.complete",  node: "measure" },
  { t: 12200, type: "run.complete" },
];

// ── Script selection ──────────────────────────────────────────────────────────

function selectScript(goal: string, demoSite: DemoSite): ScriptEvent[] {
  const g = goal.toLowerCase();
  if (demoSite === "novawear") {
    if (g.includes("women"))    return NOVAWEAR_WOMENS;
    if (g.includes("sale"))     return NOVAWEAR_SALE;
    if (g.includes("accessor")) return NOVAWEAR_ACCESSORIES;
    if (g.includes("men"))      return NOVAWEAR_MENS;
    return NOVAWEAR_WOMENS;
  }
  if (g.includes("mystery"))              return PAGETURN_MYSTERY;
  if (g.includes("sci-fi") || g.includes("sci fi") || g.includes("scifi")) return PAGETURN_SCIFI;
  if (g.includes("romance"))              return PAGETURN_ROMANCE;
  return PAGETURN_ALL;
}

export function runDemoLoop(
  goal: string,
  demoSite: DemoSite,
  dispatch: (event: RunEvent) => void
): () => void {
  const script = selectScript(goal, demoSite);
  const timeouts: ReturnType<typeof setTimeout>[] = [];
  for (const raw of script) {
    const event: RunEvent =
      raw.type === "run.start" ? { ...raw, goal: goal || raw.goal } : raw;
    const id = setTimeout(() => dispatch(event), event.t);
    timeouts.push(id);
  }
  return () => { for (const id of timeouts) clearTimeout(id); };
}
